---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ordersxv6-app
  namespace: devhub
spec:
  project: ordersxv6-app
  destinations:
    - name: local
      namespace: devhub
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - https://github.com/devhub-mad/ordersxv6-app-gitops
  
